version: "3"

networks:
  homelab:
    name: homelab
    external: true

services:
  qbittorrent:
    image: hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/app/data
      - ${DOWNLOAD_DIR}/torrent:/downloads
    networks:
      - homelab
    restart: unless-stopped
